version: '3'

services:
  ros2_relay_client:
    image: but5gera/ros2_relay_client:1.5.0
    environment:
      SEND_CLOCK: True
      ROS_DOMAIN_ID: 34
      USE_MIDDLEWARE: false
      MIDDLEWARE_ADDRESS: 192.168.60.211
      NETAPP_ADDRESS: http://192.168.60.211:5896
      MIDDLEWARE_USER: ad20f254-dc3b-406d-9f15-b73ccd47e867
      MIDDLEWARE_PASSWORD: middleware
      MIDDLEWARE_TASK_ID: cc69e01d-b8c2-4f19-8370-28c432af2762
      MIDDLEWARE_ROBOT_ID: 300c719a-1c06-4500-a13a-c2e20592b273
      TOPICS_TO_SERVER: '[{ "name": "/tf_static", "type": "tf2_msgs/msg/TFMessage", "qos": { "reliability": "RELIABLE", "history": "KEEP_ALL", "durability": "TRANSIENT_LOCAL" } }, {"name": "/synchronized/draco", "type": "point_cloud_interfaces/msg/CompressedPointCloud2"}, {"name": "/synchronized/odom", "type": "nav_msgs/msg/Odometry"},{"name": "/synchronized/imu", "type": "sensor_msgs/msg/Imu", "qos": {"preset": "SENSOR_DATA"}}]'
      TOPICS_FROM_SERVER: '[{ "name": "/map", "type": "nav_msgs/msg/OccupancyGrid", "qos": { "reliability": "RELIABLE", "history": "KEEP_LAST", "depth": 1, "durability": "TRANSIENT_LOCAL" } }]'
      TRANSFORMS_TO_SERVER: '[{"source_frame": "robot/base_footprint", "target_frame": "robot/odom", "angular_thres": 0.1, "trans_thres": 0.001, "max_publish_period": 0.1 }]'
    ports:
      -  "5896:5896"
    network_mode: host
    ipc: host

  sync:
    build: ./sync
    command: python3 /root/sync.py
    volumes: 
      - ./sync:/root
    environment:
      ROS_DOMAIN_ID: 34
    network_mode: host
    ipc: host
