version: '3'

services:

#  bbow_visualizer:
#    image: but5gera/ros2_detection_publisher:1.0.0
#    environment:
#      ROS_DOMAIN_ID: 34
#      INPUT_IMAGES: /image_raw
#      OUTPUT_IMAGES: /bounding_boxes
#      RESULTS: /res
#    network_mode: host

  decompression_node:
    build: ./../nodes
    command: python3 /root/uncompressor.py
    volumes:
      - ./../nodes/:/root
    environment:
      ROS_DOMAIN_ID: 34
    network_mode: host
    ipc: host

  visualizer_node:
    build: ./../nodes
    command: python3 /root/detection_publisher.py  # show "person" class only
    volumes:
      - ./../nodes/:/root
    environment:
      ROS_DOMAIN_ID: 34
      INPUT_IMAGES: /image_raw
      OUTPUT_IMAGES: /bounding_boxes
      RESULTS: /res
    network_mode: host
    ipc: host


  ros2_relay_client:
    image: but5gera/ros2_relay_client:1.5.0
    environment:
      SEND_CLOCK: True
      ROS_DOMAIN_ID: 34
      USE_MIDDLEWARE: false
      NETAPP_ADDRESS: http://192.168.60.211:5896
      TOPICS_TO_SERVER: '[{ "name": "/image_raw", "type": "sensor_msgs/msg/Image", "compression": "h264"}]'
      TOPICS_FROM_SERVER: '[{ "name": "/res", "type": "std_msgs/msg/String"}]'

    ports:
      -  "5896:5896"
    network_mode: host
    ipc: host

