apiVersion: v1
kind: Service
metadata:
  name: wings-teleoperation-v3
spec:
  type: NodePort
  selector:
    app: wings-teleoperation-v3
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 31011
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wings-teleoperation-v3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wings-teleoperation-v3
  template:
    metadata:
      labels:
        app: wings-teleoperation-v3
    spec:
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: wings-teleoperation-v3
          image: ghcr.io/5g-era/wings-teleoperation-v3:latest
          imagePullPolicy: Always
          resources: {}
